DROP SCHEMA IF EXISTS BCPR294_Assigment2_Post_B;
CREATE SCHEMA BCPR294_Assigment2_POST_B;
USE BCPR294_Assigment2_POST_B;

CREATE TABLE Users(
	UID VARCHAR(15) PRIMARY KEY NOT NULL,
	firstName VARCHAR(20) NOT NULL,
	lastName VARCHAR(20) NOT NULL,
	PWD VARCHAR (20) NOT NULL,
	email VARCHAR(40) NOT NULL UNIQUE KEY,
	birthday DATE NOT NULL,
	gender ENUM('M','F','O') NOT NULL
)ENGINE=InnoDB;

CREATE TABLE Post(
	PostID MEDIUMINT UNSIGNED NOT NULL  PRIMARY KEY ,
    UID VARCHAR(15) NOT NULL,
    title VARCHAR(30) NOT NUll,
    postTime DATETIME NOT NULL,
    postContent TEXT NOT NULL,
    FOREIGN KEY (UID) REFERENCES Users(UID)
)ENGINE=InnoDB;

CREATE TABLE TAG(
	tagID MEDIUMINT UNSIGNED PRIMARY KEY NOT NULL,
	UID VARCHAR(15) NOT NULL,
	PostID MEDIUMINT UNSIGNED NOT NULL,
    hasReadNotification BOOLEAN NOT NULL DEFAULT FALSE,
	FOREIGN KEY (UID) REFERENCES Users(UID),
    FOREIGN KEY (PostID) REFERENCES Post(PostID)
)ENGINE=InnoDB;